services:
  db:
    image: postgres:16-alpine
    container_name: postgres-db

    environment:
      POSTGRES_DB: labdb
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass123
      TZ: Asia/Jakarta

    ports:
      - "5432:5432"

    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./backup:/backup
      - ./logs:/var/log/postgresql

    networks:
      - db-net

    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pens.ac.id
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    volumes:
      - pgadmin-data:/var/lib/pgadmin

    networks:
      - db-net

    depends_on:
      - db

volumes:
  pg-data:
  pgadmin-data:

networks:
  db-net:
